const RESUME_ACTION_TYPES = {
    SET_CURRENT_RESUME: 'SET_CURRENT_RESUME',
    SET_RESUME_ERROR: 'SET_RESUME_ERROR',
    SET_CURRENT_RECOMMENDATION_RESUME: 'SET_CURRENT_RECOMMENDATION_RESUME',
    SET_RECOMMENDATION_RESUME_ERROR: 'SET_RECOMMENDATION_RESUME_ERROR',
    SET_CURRENT_COMMUNITY_RESUME: 'SET_CURRENT_COMMUNITY_RESUME',
    SET_COMMUNITY_RESUME_ERROR: 'SET_COMMUNITY_RESUME_ERROR'
};

export default RESUME_ACTION_TYPES;